Optimized for better user help & performance

diff --git a/scripts/proxdad b/scripts/proxdad
--- a/scripts/proxdad
+++ b/scripts/proxdad
@@ -28,13 +28,13 @@ Commands:
   off                   Turn off ProxDad
   status                Get the status of ProxDad
   set                   Set ProxDad settings
-      -h <host>           Set proxy host
-      -p <port>           Set proxy port
-      -u <username>       Set proxy username
-      -w <password>       Set proxy password
+    -i <host>           Set proxy host
+    -p <port>           Set proxy port
+    -u <username>       Set proxy username
+    -w <password>       Set proxy password
 
-ProxDad $proxdad_version installed at $proxdad_installation_path
-ProxDad settings specified in $proxdad_config_file
+ProxDad $proxdad_version is installed at $proxdad_installation_path
+ProxDad settings are specified in $proxdad_config_file
 
 For bug reports, please visit: 
 https://github.com/abhisheksinghforsure/proxdad/issues
@@ -42,7 +42,7 @@ https://github.com/abhisheksinghforsure/proxdad/issues
 This is free software; see the license for copying conditions. There is NO
 warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 EOF
-    exit 1
+    exit 0
 }
 
 version() {
@@ -51,7 +51,7 @@ version() {
 }
 
 # Parse command-line options
-[[ $# -eq 0 ]] && { echo "Error: No command specified."; usage; }
+[[ $# -eq 0 ]] && { usage; }
 
 case $1 in
     -h|--help) usage ;;
@@ -59,6 +59,9 @@ case $1 in
     on) onpxd ;;
     off) offpxd ;;
     status) statuspxd ;;
-    set) setpxd "$@" ;;
-    *) echo "Error: Invalid command specified."; usage ;;
+    set) shift; setpxd "$@" ;;
+    *) 
+        echo "Error: Invalid command specified."; 
+        exit 1 
+        ;;
 esac
