Add Bash shell check to ensure script is executed in a compatible environment

diff --git a/include/_utilspxd b/include/_utilspxd
--- a/include/_utilspxd
+++ b/include/_utilspxd
@@ -13,6 +13,12 @@ readonly RED="\e[1;31m"
 readonly RESET="\e[0m"
 readonly CIRCLE="●"
 
+# Check if the script is being run with Bash
+if [ -z "$BASH_VERSION" ]; then
+    printf "${RED}[ERROR]${RESET} Use 'Bash' to run this script\n" >&2
+    exit 1
+fi
+
 # Prevent root user from executing script
 if [[ $EUID -eq 0 ]]; then
     echo -e "${RED}[ERROR]${RESET} Do not use root privileges"
